version: '3.8'
services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      volumes:
        - .:/var/www/html
      depends_on:
        - db
      user: "www-data"

    db:
      platform: linux/x86_64
      # platform: linux/amd64
      image: mysql:8.0.26
      environment:
        MYSQL_DATABASE: admin
        # MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./storage/dbdata:/var/lib/mysql
      ports:
        - 33066:3306
